---
title: "NINJA Output"
author: "Casey Sakamoto"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r,include=FALSE}
library(devtools)
library(Hmisc)
library(tableone)
library(ggplot2)
library(ggsci)
library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
library(ggalluvial)

df <- read.csv("S:/Brinton/Nephrology/2024.03.06 Shih NINJA - RAI mephrotoxin exposures in ICU and clincal course retrospective cohort/data/data_d.csv")
#df <- read.csv("H:/From CBC Individual/BrintonJ/AKI/2024.03.06 Shih NINJA - RAI mephrotoxin exposures in ICU and clincal course retrospective cohort/data/data_d.csv")

df[df =="."] <- NA

# CHANGE VARS FROM peak back to initial
#########################################

vars_1<-c("age_year",
"Diagnosis_Category",
"Admission_location",
"Procedure",
"CKD_gte_stage_3",
"Kidney_transplant",
"previous_AKI",
"single_kidney",
"LOS_ICU",
"death",
"Vancomycin_exp",
"Zosyn_exp",
"Antivirals_exp",
"Contrast_exp",
"NSAID_ketorolac_exp",
"Calcineurin_inhibitors_exp",
"supratherapeutic_vancomyci",
"gentamicin_trough_2",
"tacrolimus_level_15",
"cyclosporine_level_300"
)

nonnormal_vars<-c("age_year",
"Diagnosis_Category",
"Admission_location",
"Procedure",
"CKD_gte_stage_3",
"Kidney_transplant",
"previous_AKI",
"single_kidney",
"LOS_ICU",
"death",
"Vancomycin_exp",
"Zosyn_exp",
"Antivirals_exp",
"Contrast_exp",
"NSAID_ketorolac_exp",
"Calcineurin_inhibitors_exp",
"supratherapeutic_vancomyci",
"gentamicin_trough_2",
"tacrolimus_level_15",
"cyclosporine_level_300"
)

df$peak_AKI_2cat = ifelse(df$highest_aki_stage_for_this == "Stage 1 (0.3 increase in Daily Scr  or Daily Scr 1.5 - 1.9 times baseline)", "Stage 1", "Stage 2 or 3" )
df$NSAID_ketorolac_exp = ifelse(df$Ketorolac_exp == "Yes" | df$NSAID_exp == "Yes", "Yes", "No")

tab1<-CreateTableOne(vars = vars_1, data = df)
# nonnormal_vars<-tab1<-CreateTableOne(vars = vars_1, strata = c("Outcome_of_interest__AKI__Y_1__N"), data = df)

tab1_overall<-CreateTableOne(vars = vars_1, data = df, strata="initial_aki_stage_2cat", addOverall=TRUE)
# print(tab1)
tab1Mat_overall <- print(tab1_overall, nonnormal = nonnormal_vars, quote = FALSE, noSpaces = TRUE, printToggle = FALSE, )
tab1<-CreateTableOne(vars = vars_1, data = df)
# nonnormal_vars<-tab1<-CreateTableOne(vars = vars_1, strata = c("Outcome_of_interest__AKI__Y_1__N"), data = df)

tab1_overall<-CreateTableOne(vars = vars_1, data = df, strata="initial_aki_stage_2cat", addOverall=TRUE)
# print(tab1)
tab1Mat_overall <- print(tab1_overall, nonnormal = nonnormal_vars, quote = FALSE, noSpaces = TRUE, printToggle = FALSE, )

##################################################################################

##################################################################################
# NOTE: Table 2: Frequency of exposures to specific neprotoxins and associated AKI stage
# information is contained in barcharts below, and mentioned worth taking out of output
# by John. The next table 2 in the manuscript is 
# Table 2 NAKI outcomes data by NTMx 
##################################################################################
#new dataframe including only the individuals
# Load the dplyr package
library(dplyr)
df$dialysis = ifelse(df$indication_for_dialysis___1 == "Checked" | 
                     df$indication_for_dialysis___2 == "Checked" |
                     df$indication_for_dialysis___3 == "Checked" |
                     df$indication_for_dialysis___4 == "Checked" |
                     df$indication_for_dialysis___5 == "Checked" , "Any Dialysis", "No Dialysis")
# Assuming data_d is your original data frame
df_vanc <- df %>%
  filter(Vancomycin_exp == "Yes")

vars_2<-c("count_NTMX",
"time_flag_to_AKI",
"LOS_ICU",
"CKD_gte_stage_3",
"Kidney_transplant",
"previous_AKI",
"single_kidney",
"highest_aki_stage_for_this",
"pct_cre_inc",
"dialysis_needed_after_hosp",
"dialysis",
"ecmo_during_hospitalizatio",
"death"

)

nonnormal_vars<-c("count_NTMX",
"time_flag_to_AKI",
"LOS_ICU",
"CKD_gte_stage_3",
"Kidney_transplant",
"previous_AKI",
"single_kidney",
"highest_aki_stage_for_this",
"pct_cre_inc",
"dialysis_needed_after_hosp",
"dialysis",
"indication_for_dialysis",
"ecmo_during_hospitalizatio",
"death"

)

## Vector of categorical variables that need transformation
catVars <- c("dialysis_needed_after_hosp",
"dialysis",
"indication_for_dialysis",
"ecmo_during_hospitalizatio")


tab2_vanc<-CreateTableOne(vars = vars_2, data = df_vanc)

tab2Mat_vanc <- print(tab2_vanc, showAllLevels = TRUE, nonnormal = nonnormal_vars, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)


##################################################################################
# TABLE 2
# need count_ntmx
# from sas code figures prog
data_d = df
# Define the function to generate the datasets
stack_Tab2 <- function(dataset, Exp, exp_label) {
  # Filter the dataset where the Exp column is equal to 1 (exposure event)
  dataset <- dataset %>% 
    filter(!!sym(Exp) == "Yes")  # Filter: where Exp = 1 (e.g., Vancomycin_exp = 1)

  # Create new variables based on the exposure label and corresponding columns
  dataset <- dataset %>%
    mutate(
      # NTMX column to store the exposure label
      NTMX = exp_label,  # NTMX = "Vancomycin", "Zosyn", etc.
      
      # count_NTMX column to store count of exposure events
      count_NTMX = !!sym(paste0("count_", exp_label)),  # count_Vancomycin, count_Zosyn, etc.
      
      # ID_NTMX_pre column to store the pre-exposure identifier
      ID_NTMX_pre = !!sym(paste0(exp_label, "_exp_pre")),  # Vancomycin_exp_pre, Zosyn_exp_pre, etc.
      
      # ID_NTMX_post column to store the post-exposure identifier
      ID_NTMX_post = !!sym(paste0(exp_label, "_exp_post")),  # Vancomycin_exp_post, Zosyn_exp_post, etc.
      
      # count_NTMX_pre column to store count of exposure events before exposure
      count_NTMX_pre = !!sym(paste0("count_", exp_label, "_pre")),  # count_Vancomycin_pre, count_Zosyn_pre, etc.
      
      # count_NTMX_post column to store count of exposure events after exposure
      count_NTMX_post = !!sym(paste0("count_", exp_label, "_post"))  # count_Vancomycin_post, count_Zosyn_post, etc.
      
      # supra_NTMX_pre column to store supratherapeutic exposure status before exposure
      # supra_NTMX_pre = !!sym(paste0("Supra_", exp_label, "_pre"))  # Supra_Vancomycin_pre, Supra_Zosyn_pre, etc.
    )  # Creating all the new variables as per the original SAS logic
  
  return(dataset)
}
# quick dataset typo issues
data_d$Ketrolac_exp_pre = data_d$Ketorolac_exp_pre
data_d$Ketrolac_exp_post = data_d$Ketorolac_exp_post
data_d$Calcineurin_exp_pre = data_d$Calcineurin_inhibitors_exp_pre
data_d$Calcineurin_exp_post = data_d$Calcineurin_inhibitors_exp_post

# combine keterolac and nsaid
data_d$count_NSAID_ketorolac = data_d$count_NSAID + data_d$count_Ketrolac
data_d$NSAID_ketorolac_exp_pre = ifelse(data_d$Ketorolac_exp_pre == 1 | data_d$NSAID_exp_pre  == 1, 1, 0)
data_d$NSAID_ketorolac_exp_post = ifelse(data_d$Ketorolac_exp_post == 1 | data_d$NSAID_exp_post == 1, 1, 0)
data_d$count_NSAID_ketorolac_pre = data_d$count_NSAID_pre + data_d$count_Ketrolac_pre
data_d$count_NSAID_ketorolac_post = data_d$count_NSAID_post + data_d$count_Ketrolac_post
# Apply the function to each exposure group and combine the dataset
stack_T2 <- bind_rows(
  stack_Tab2(data_d, "Vancomycin_exp", "Vancomycin"),
  stack_Tab2(data_d, "Zosyn_exp", "Zosyn"),
  stack_Tab2(data_d, "Antivirals_exp", "Antivirals"),
  stack_Tab2(data_d, "Contrast_exp", "Contrast"),
  stack_Tab2(data_d, "NSAID_ketorolac_exp", "NSAID_ketorolac"),
  stack_Tab2(data_d, "Calcineurin_inhibitors_exp", "Calcineurin")
)

# Original Vars -- need to combine the indications for dialysis
vars_22<-c("count_NTMX",
"time_flag_to_AKI",
"LOS_ICU",
"CKD_gte_stage_3",
"Kidney_transplant",
"previous_AKI",
"single_kidney",
"highest_aki_stage_for_this",
"pct_cre_inc",
"dialysis_needed_after_hosp",
"dialysis",
"ecmo_during_hospitalizatio",
"death"
)

# output table
tab2_overall<-CreateTableOne(vars = vars_22, data = stack_T2, strata="NTMX", factorVars= catVars)
# print(tab1)
tab2Mat_overall <- print(tab2_overall, nonnormal = nonnormal_vars, quote = FALSE, noSpaces = TRUE, printToggle = FALSE, factorVars= catVars)


##################################################################################

##################################################################################
# TABLE 3 Chron of Neph Exp
# List of variable names for the table
vars_3 <- c("ID_NTMX_pre", "ID_NTMX_post", "count_NTMX_pre", "count_NTMX_post", "time_flag_to_AKI",  "vaso_pre")

# List of non-normal variables for the table
nonnormal_vars <- c("ID_NTMX_pre", "ID_NTMX_post", "count_NTMX_pre", "count_NTMX_post", "time_flag_to_AKI",  "vaso_pre")

## Vector of categorical variables that need transformation
catVars <- c("ID_NTMX_pre", "ID_NTMX_post", "vaso_pre")


tab3<-CreateTableOne(vars = vars_3, data = stack_T2, factorVars= catVars)
# nonnormal_vars<-tab1<-CreateTableOne(vars = vars_1, strata = c("Outcome_of_interest__AKI__Y_1__N"), data = df)

tab3_overall<-CreateTableOne(vars = vars_3, data = stack_T2, strata="NTMX", factorVars= catVars)
# print(tab1)
tab3Mat_overall <- print(tab3_overall, nonnormal = nonnormal_vars, quote = FALSE, noSpaces = TRUE, printToggle = FALSE, factorVars= catVars)

##################################################################################

##################################################################################
# Fig 2
# Deriving supra_NTMX_pre column in stack_T2
stack_T2 <- stack_T2 %>%
  mutate(
    supra_NTMX_pre = case_when(
      NTMX == "Vancomycin" ~ Supra_Vancomycin_pre,
      NTMX == "Calcineurin" ~ Supra_Calcineurin_pre,
      TRUE ~ NA_real_
    )
  )


# Filtering data for Vancomycin
fig2_supra_vanc <- stack_T2 %>%
  filter(NTMX == "Vancomycin")

# Compute counts and proportions
fig2_supra_vanc <- fig2_supra_vanc %>%
  count(supra_NTMX_pre, initial_aki_stage_2cat) %>%
  group_by(supra_NTMX_pre) %>%
  mutate(percent = round(n / sum(n) * 100, 2))

# Absolute frequency stacked bar chart with count labels
p1 = ggplot(fig2_supra_vanc, aes(y = factor(supra_NTMX_pre), x = n, fill = initial_aki_stage_2cat)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = n), position = position_stack(vjust = 0.5), size = 4, color = "white") +
  labs(y = "Supra NTMX Pre", x = "Count", fill = "AKI Stage") +
  ggtitle("Number of patients by exposure to sup levels of Vanc pre NINJA flag and stage of initial aki") +
  scale_fill_grey()

# Relative frequency stacked bar chart with percentage labels
p2 = ggplot(fig2_supra_vanc, aes(y = factor(supra_NTMX_pre), x = percent, fill = initial_aki_stage_2cat)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(aes(label = paste0(percent, "%")), 
            position = position_fill(vjust = 0.5), size = 4, color = "white") +
  labs(y = "Supra NTMX Pre", x = "Proportion", fill = "AKI Stage") +
  ggtitle("Percent of patients by exposure to sup levels of Vanc pre NINJA flag and stage of initial aki") +
  scale_fill_grey()



# Filtering data for Calcineurin inhibitors
fig2_supra_calc <- stack_T2 %>%
  filter(NTMX == "Calcineurin")

# Compute counts and proportions
fig2_supra_calc <- fig2_supra_calc %>%
  count(supra_NTMX_pre, initial_aki_stage_2cat) %>%
  group_by(supra_NTMX_pre) %>%
  mutate(percent = round(n / sum(n) * 100, 2))

# Absolute frequency stacked bar chart with count labels
p3 = ggplot(fig2_supra_calc, aes(y = factor(supra_NTMX_pre), x = n, fill = initial_aki_stage_2cat)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = n), position = position_stack(vjust = 0.5), size = 4, color = "white") +
  labs(y = "Supra NTMX Pre", x = "Count", fill = "AKI Stage") +
  ggtitle("Number of patients by exposure to sup levels of Calc pre NINJA flag and stage of initial aki") +
  scale_fill_grey()

# Relative frequency stacked bar chart with percentage labels
p4 = ggplot(fig2_supra_calc, aes(y = factor(supra_NTMX_pre), x = percent, fill = initial_aki_stage_2cat)) +
  geom_bar(stat = "identity", position = "fill") +
  geom_text(aes(label = paste0(percent, "%")), 
            position = position_fill(vjust = 0.5), size = 4, color = "white") +
  labs(y = "Supra NTMX Pre", x = "Proportion", fill = "AKI Stage") +
  ggtitle("Percent of patients by exposure to sup levels of Calc pre NINJA flag and stage of initial aki") +
  scale_fill_grey()


##################################################################################

##################################################################################
# Stacked bars
custom_exposure_order <- c(
  "Vancomycin_exp",
  "Zosyn_exp",
  "Antivirals_exp",
  "Contrast_exp",
  "NSAID_ketorolac_exp",
  "Calcineurin_inhibitors_exp"
)

# Figure DF
df_bar = df %>% select(record_id, initial_aki_stage_2cat, Vancomycin_exp, Zosyn_exp, Antivirals_exp, Contrast_exp, NSAID_ketorolac_exp, Calcineurin_inhibitors_exp)


# Convert from wide to long format
exposure_rf_stacked_df <- df_bar %>%
  pivot_longer(cols = -c(record_id, initial_aki_stage_2cat), 
               names_to = "Exposure", 
               values_to = "Exposure_Status") %>%
  filter(Exposure_Status == "Yes")  # Keep only "Yes" exposures

# Generate the stacked bar chart
# Compute proportions within each exposure group
exposure_rf_stacked_df_summary <- exposure_rf_stacked_df %>%
  count(Exposure, initial_aki_stage_2cat) %>%
  group_by(Exposure) %>%
  mutate(prop = n / sum(n) * 100, label = sprintf("%.2f%%", prop))

# Ensure factors are ordered for proper plotting
exposure_rf_stacked_df_summary$Exposure <- factor(exposure_rf_stacked_df_summary$Exposure, levels = rev(custom_exposure_order))
exposure_rf_stacked_df_summary$initial_aki_stage_2cat <- factor(exposure_rf_stacked_df_summary$initial_aki_stage_2cat, levels= c("Stage 1", "Stage 2 or 3"), labels = c("Stage 1", "Stage 2 or 3"))

# Generate the horizontal stacked bar chart
sb1 = ggplot(exposure_rf_stacked_df_summary, aes(y = Exposure, x = prop, fill = initial_aki_stage_2cat)) +
  geom_col(position = "stack", width = 0.7) +  # Use geom_col() for precomputed values
  geom_text(aes(label = sprintf("%.1f%%", prop)), 
            position = position_stack(vjust = 0.5),  # Center labels
            color = "white", size = 4) +  # Adjust text size & color
  scale_x_continuous(labels = scales::percent_format(scale = 1)) +  # Convert to percent
  labs(title = "Proportion of Patients by Exposure and Initial AKI Stage",
       x = "Percent of Row Frequency",
       y = "NTMx Exposure",
       fill = "Initial AKI Stage") +
  scale_fill_grey()


# Generate frequency-based stacked bar chart
sb2 = ggplot(exposure_rf_stacked_df_summary, aes(y = Exposure, x = n, fill = initial_aki_stage_2cat)) +
  geom_col(position = "stack", width = 0.7) +  # Stacked bars with raw counts
  geom_text(aes(label = n), 
            position = position_stack(vjust = 0.5),  # Center labels
            color = "white", size = 4) +  # Adjust text size & color
  labs(title = "Number of Patients by Exposure and Initial AKI Stage",
       x = "Patient Count",
       y = "NTMx Exposure",
       fill = "Initial AKI Stage") +
  scale_fill_grey()

sb2
##################################################################################

##################################################################################
# Alluvial plots
# data prep for the laneplots/alluvials -- gona import data_day_exp from the lane plots generated in p0005
# Assuming 'play' is your data frame in R
# Function to determine the first day of exposure for a drug
# Create the exposure indicator columns
data_d$Vancomycin_exp <- ifelse(data_d$count_40_Vancomycin != 0, 1, 0)
data_d$Zosyn_exp <- ifelse(data_d$count_33_Zosyn_Piperacillin != 0, 1, 0)
data_d$Aminoglycosides_exp <- ifelse(data_d$count_26_Gentamicin != 0 | data_d$count_38_Tobramycin != 0, 1, 0)
data_d$Amphotericin_exp <- ifelse(data_d$count_12_Ambisome != 0, 1, 0)
data_d$Antivirals_exp <- ifelse(
  data_d$count_48_Acyclovir != 0 | data_d$count_19_Cidofovir != 0 | 
    data_d$count_25_Ganciclovir != 0 | data_d$count_63_Tenofovir != 0 | 
    data_d$count_45_Valganciclovir != 0 | data_d$count_46_Valacyclovir != 0, 1, 0
)
data_d$Contrast_exp <- ifelse(data_d$count_24_Gado_Derivatives != 0 | data_d$count_28_Iodinated_CA != 0, 1, 0)
data_d$NSAID_exp <- ifelse(data_d$count_27_Ibuprofen != 0, 1, 0)
data_d$Ketorolac_exp <- ifelse(data_d$count_47_Ketorolac != 0, 1, 0)
data_d$Celecoxib_exp <- ifelse(data_d$count_51_Celecoxib != 0, 1, 0)
data_d$Calcineurin_inhibitors_exp <- ifelse(
  data_d$count_36_Tacrolimus != 0 | data_d$count_21_Cyclosporine != 0, 1, 0
)
data_d$Sirolimus_exp <- ifelse(data_d$count_34_Sirolimus != 0, 1, 0)
data_d$AED_exp <- ifelse(data_d$count_39_Topiramate != 0 | data_d$count_41_Zonisamide != 0, 1, 0)
data_d$ACE_ARB_exp <- ifelse(
  data_d$count_14_Captopril != 0 | data_d$count_42_Enalapril != 0 | 
    data_d$count_53_Enalaprilat != 0 | data_d$count_43_Lisinopril != 0 | 
    data_d$count_55_Losartan != 0 | data_d$count_64_Valsartan != 0, 1, 0
)

# Function to determine the first day of exposure for a drug
first_exposure_day <- function(ntmx_3, ntmx_2, ntmx_1, ntmx_0, ntmx_1d, ntmx_2d, ntmx_3d, ntmx_4d, ntmx_5d, ntmx_6d, ntmx_7d) {
  # Convert factors to logical TRUE/FALSE based on "Checked" level
  ntmx_3 <- ntmx_3 == "Checked"
  ntmx_2 <- ntmx_2 == "Checked"
  ntmx_1 <- ntmx_1 == "Checked"
  ntmx_0 <- ntmx_0 == "Checked"
  ntmx_1d <- ntmx_1d == "Checked"
  ntmx_2d <- ntmx_2d == "Checked"
  ntmx_3d <- ntmx_3d == "Checked"
  ntmx_4d <- ntmx_4d == "Checked"
  ntmx_5d <- ntmx_5d == "Checked"
  ntmx_6d <- ntmx_6d == "Checked"
  ntmx_7d <- ntmx_7d == "Checked"

  # Determine first day of exposure
  if (ntmx_3) return(-3)
  if (ntmx_2) return(-2)
  if (ntmx_1) return(-1)
  if (ntmx_0) return(0)
  if (ntmx_1d) return(1)
  if (ntmx_2d) return(2)
  if (ntmx_3d) return(3)
  if (ntmx_4d) return(4)
  if (ntmx_5d) return(5)
  if (ntmx_6d) return(6)
  if (ntmx_7d) return(7)
  
  return(NA) # If no exposure was found
}


# Apply first_exposure_day function
data_d$day_Vancomycin_exp <- mapply(first_exposure_day, data_d$ntmx_3_days_prior___40, data_d$ntmx_2_days_prior___40, 
                                     data_d$ntmx_1_days_prior___40, data_d$ntmx_day_of___40, data_d$ntmx_day_of_1___40, 
                                     data_d$ntmx_day_of_2___40, data_d$ntmx_day_of_3___40, data_d$ntmx_day_of_4___40, 
                                     data_d$ntmx_day_of_5___40, data_d$ntmx_day_of_6___40, data_d$ntmx_day_of_7___40)

# vanc exposure df
vanc_exp_df = data_d %>% select(record_id, day_Vancomycin_exp, ntmx_3_days_prior___40,ntmx_2_days_prior___40, 
                                     ntmx_1_days_prior___40, ntmx_day_of___40, ntmx_day_of_1___40, 
                                     ntmx_day_of_2___40, ntmx_day_of_3___40, ntmx_day_of_4___40, 
                                     ntmx_day_of_5___40, ntmx_day_of_6___40, ntmx_day_of_7___40) %>% filter(!is.na(day_Vancomycin_exp)) %>%
  select(-day_Vancomycin_exp)



# long
# Reshape the dataset to long format
vanc_long_df <- vanc_exp_df %>%
  pivot_longer(cols = starts_with("ntmx"),
               names_to = "timepoint",
               values_to = "status")


vanc_long_df = vanc_long_df %>% mutate(tp = case_when(timepoint == "ntmx_3_days_prior___40" ~ -3,
                                                             timepoint == "ntmx_2_days_prior___40" ~ -2,
                                                             timepoint == "ntmx_1_days_prior___40" ~ -1,
                                                             timepoint == "ntmx_day_of___40" ~ 0,
                                                             timepoint == "ntmx_day_of_1___40" ~ 1,
                                                             timepoint == "ntmx_day_of_2___40" ~ 2,
                                                             timepoint == "ntmx_day_of_3___40" ~ 3,
                                                             timepoint == "ntmx_day_of_4___40" ~ 4,
                                                             timepoint == "ntmx_day_of_5___40" ~ 5,
                                                             timepoint == "ntmx_day_of_6___40" ~ 6,
                                                             timepoint == "ntmx_day_of_7___40" ~ 7))

order_df <- vanc_long_df %>%
  arrange(record_id, tp) %>%  # Ensure chronological order
  mutate(first_letter = substr(status, 1, 1)) %>%  # Extract first letter
  group_by(record_id) %>%
  summarise(order = paste(first_letter, collapse = ""), .groups = "drop")

vanc_long_df = left_join(vanc_long_df, order_df)
vanc_long_df$freq = 1

vanc_long_df = left_join(vanc_long_df, data_d %>% select(record_id, initial_aki_stage, initial_aki_stage_2cat))
# alluvial plot
vanc_alluvial = ggplot(vanc_long_df,
       aes(x = tp, stratum = status, alluvium = record_id,
           fill = status, y = freq)) +
  geom_flow() + scale_x_continuous(breaks = -3:7)+ 
  geom_stratum(aes(fill = status)) +
  geom_label(stat = "stratum",aes( label = after_stat(count)),fill = "white", size = 3) + 
  ggtitle("Vancomycin Exposure") + scale_fill_grey() + guides(label="none")

vanc_alluvial
# alluvial plot by initial aki stage
# vanc_alluvial2 = ggplot(vanc_long_df,
#        aes(x = tp, stratum = status, alluvium = record_id,
#            fill = initial_aki_stage_2cat, label = status, y = freq)) +
#   geom_flow() + scale_x_continuous(breaks = -3:7)+ 
#   geom_stratum(aes(fill = status)) +
#   geom_label(aes(fill = status),stat = "stratum", size = 3) +
#   ggtitle("Vancomycin Exposure by initial AKI stage") + scale_fill_grey()

# table
vanc_exp_t = vanc_long_df %>% group_by(tp,status) %>% summarise(freq = n(),
                                                    rf = freq/56)
##################################################################################
# NSAID ALLUVIAL
# Apply first_exposure_day function
data_d$day_NSAID_exp <- mapply(first_exposure_day, data_d$ntmx_3_days_prior___27, data_d$ntmx_2_days_prior___27, 
                                     data_d$ntmx_1_days_prior___27, data_d$ntmx_day_of___27, data_d$ntmx_day_of_1___27, 
                                     data_d$ntmx_day_of_2___27, data_d$ntmx_day_of_3___27, data_d$ntmx_day_of_4___27, 
                                     data_d$ntmx_day_of_5___27, data_d$ntmx_day_of_6___27, data_d$ntmx_day_of_7___27)

# NSAID exposure df
nsaid_exp_df = data_d %>% select(record_id, day_NSAID_exp, ntmx_3_days_prior___27,ntmx_2_days_prior___27, 
                                     ntmx_1_days_prior___27, ntmx_day_of___27, ntmx_day_of_1___27, 
                                     ntmx_day_of_2___27, ntmx_day_of_3___27, ntmx_day_of_4___27, 
                                     ntmx_day_of_5___27, ntmx_day_of_6___27, ntmx_day_of_7___27) %>% filter(!is.na(day_NSAID_exp)) %>%
  select(-day_NSAID_exp)

# Reshape the dataset to long format
nsaid_long_df <- nsaid_exp_df %>%
  pivot_longer(cols = starts_with("ntmx"),
               names_to = "timepoint",
               values_to = "status")

nsaid_long_df = nsaid_long_df %>% mutate(tp = case_when(timepoint == "ntmx_3_days_prior___27" ~ -3,
                                                        timepoint == "ntmx_2_days_prior___27" ~ -2,
                                                        timepoint == "ntmx_1_days_prior___27" ~ -1,
                                                        timepoint == "ntmx_day_of___27" ~ 0,
                                                        timepoint == "ntmx_day_of_1___27" ~ 1,
                                                        timepoint == "ntmx_day_of_2___27" ~ 2,
                                                        timepoint == "ntmx_day_of_3___27" ~ 3,
                                                        timepoint == "ntmx_day_of_4___27" ~ 4,
                                                        timepoint == "ntmx_day_of_5___27" ~ 5,
                                                        timepoint == "ntmx_day_of_6___27" ~ 6,
                                                        timepoint == "ntmx_day_of_7___27" ~ 7))

order_df <- nsaid_long_df %>%
  arrange(record_id, tp) %>%  # Ensure chronological order
  mutate(first_letter = substr(status, 1, 1)) %>%  # Extract first letter
  group_by(record_id) %>%
  summarise(order = paste(first_letter, collapse = ""), .groups = "drop")

nsaid_long_df = left_join(nsaid_long_df, order_df)
nsaid_long_df$freq = 1

nsaid_long_df = left_join(nsaid_long_df, data_d %>% select(record_id, initial_aki_stage, initial_aki_stage_2cat))

# Alluvial plot
nsaid_alluvial = ggplot(nsaid_long_df,
                        aes(x = tp, stratum = status, alluvium = record_id,
                            fill = status, y = freq)) +
  geom_flow() + scale_x_continuous(breaks = -3:7)+ 
  geom_stratum(aes(fill = status)) +
  geom_label(stat = "stratum", aes(label = after_stat(count)), fill = "white", size = 3) + 
  ggtitle("NSAID Exposure") + scale_fill_grey() + guides(label="none")

nsaid_alluvial

# Summary table
nsaid_exp_t = nsaid_long_df %>%
  group_by(tp, status) %>%
  summarise(freq = n(), rf = freq / length(is.na(freq)))

##################################################################################
# NSAID + KET
data_d$day_Ketorolac_exp <- mapply(first_exposure_day, data_d$ntmx_3_days_prior___47, data_d$ntmx_2_days_prior___47, 
                                   data_d$ntmx_1_days_prior___47, data_d$ntmx_day_of___47, data_d$ntmx_day_of_1___47, 
                                   data_d$ntmx_day_of_2___47, data_d$ntmx_day_of_3___47, data_d$ntmx_day_of_4___47, 
                                   data_d$ntmx_day_of_5___47, data_d$ntmx_day_of_6___47, data_d$ntmx_day_of_7___47)

combo_exp_df <- data_d %>% filter(NSAID_ketorolac_exp == "Yes") %>%
  select(record_id,
         # NSAID ___27
         ntmx_3_days_prior___27, ntmx_2_days_prior___27, ntmx_1_days_prior___27, ntmx_day_of___27,
         ntmx_day_of_1___27, ntmx_day_of_2___27, ntmx_day_of_3___27, ntmx_day_of_4___27,
         ntmx_day_of_5___27, ntmx_day_of_6___27, ntmx_day_of_7___27,
         # Ketorolac ___47
         ntmx_3_days_prior___47, ntmx_2_days_prior___47, ntmx_1_days_prior___47, ntmx_day_of___47,
         ntmx_day_of_1___47, ntmx_day_of_2___47, ntmx_day_of_3___47, ntmx_day_of_4___47,
         ntmx_day_of_5___47, ntmx_day_of_6___47, ntmx_day_of_7___47) %>%
  # Combine NSAID and Ketorolac columns into unified values:
  mutate(across(-record_id, ~ . == "Checked")) %>%
  rowwise() %>%
  mutate(
    ntmx_3 = any(ntmx_3_days_prior___27, ntmx_3_days_prior___47, na.rm = TRUE),
    ntmx_2 = any(ntmx_2_days_prior___27, ntmx_2_days_prior___47, na.rm = TRUE),
    ntmx_1 = any(ntmx_1_days_prior___27, ntmx_1_days_prior___47, na.rm = TRUE),
    ntmx_0 = any(ntmx_day_of___27, ntmx_day_of___47, na.rm = TRUE),
    ntmx_1d = any(ntmx_day_of_1___27, ntmx_day_of_1___47, na.rm = TRUE),
    ntmx_2d = any(ntmx_day_of_2___27, ntmx_day_of_2___47, na.rm = TRUE),
    ntmx_3d = any(ntmx_day_of_3___27, ntmx_day_of_3___47, na.rm = TRUE),
    ntmx_4d = any(ntmx_day_of_4___27, ntmx_day_of_4___47, na.rm = TRUE),
    ntmx_5d = any(ntmx_day_of_5___27, ntmx_day_of_5___47, na.rm = TRUE),
    ntmx_6d = any(ntmx_day_of_6___27, ntmx_day_of_6___47, na.rm = TRUE),
    ntmx_7d = any(ntmx_day_of_7___27, ntmx_day_of_7___47, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  select(record_id, starts_with("ntmx_")) %>%
  mutate(across(starts_with("ntmx_"), ~ ifelse(. == TRUE, "Checked", "Unchecked")))


# Step 2: Pivot to long format
long_df <- combo_exp_df %>%
  pivot_longer(cols = starts_with("ntmx_"),
               names_to = "timepoint",
               values_to = "status")

# Step 3: Assign timepoint values
long_df <- long_df %>%
  mutate(tp = case_when(
    timepoint == "ntmx_3" ~ -3,
    timepoint == "ntmx_2" ~ -2,
    timepoint == "ntmx_1" ~ -1,
    timepoint == "ntmx_0" ~ 0,
    timepoint == "ntmx_1d" ~ 1,
    timepoint == "ntmx_2d" ~ 2,
    timepoint == "ntmx_3d" ~ 3,
    timepoint == "ntmx_4d" ~ 4,
    timepoint == "ntmx_5d" ~ 5,
    timepoint == "ntmx_6d" ~ 6,
    timepoint == "ntmx_7d" ~ 7
  ))


long_df$freq <- 1
long_df = long_df %>% filter(!is.na(tp))

# Add AKI info if available
if ("initial_aki_stage_2cat" %in% colnames(data_d)) {
  long_df <- left_join(long_df, data_d %>% select(record_id, initial_aki_stage, initial_aki_stage_2cat))
}

# Step 5: Create the alluvial plot
nsaid_ketorolac_alluvial <- ggplot(long_df,
                                   aes(x = tp, stratum = status, alluvium = record_id,
                                       fill = status, y = freq)) +
  geom_flow() +
  geom_stratum(aes(fill = status)) +
  geom_label(stat = "stratum", aes(label = after_stat(count)), fill = "white", size = 3) +
  scale_x_continuous(breaks = -3:7) +
  ggtitle("NSAIDs or Ketorolac Exposure") +
  scale_fill_grey(start = 0.3, end = 0.7) +
  guides(label = "none")

# Show plot
nsaid_ketorolac_alluvial

# Summary table
nsaid_ket_exp_t = long_df %>%
  group_by(tp, status) %>%
  summarise(freq = n(), rf = freq / length(is.na(freq)))
##################################################################################
##################################################################################
```

```{r output, results='asis'}
# Table 1 Demographics by Initial AKI Stage
kbl(tab1Mat_overall, booktabs = T) %>% kable_classic()%>% kable_styling("striped")

# Figure 1 Rate of acute kidney injury (AKI) stages by medication exposure group 
sb1;sb2

# Note Original Table 2 John commented to remove as info was redundant with stacked bars
# Table 3 -> 2 NAKI Outcomes Data by NTMx
kbl(tab2Mat_overall, booktabs = T) %>% kable_classic()%>% kable_styling("striped")

# Table 3 Chronology of Nephrotoxin exposure
kbl(tab3Mat_overall, booktabs = T) %>% kable_classic()%>% kable_styling("striped")

# Figure 2 Supratherapeutic drug levels correlating to AKI stages
p1;p2;p3;p4

# Alluvials
vanc_alluvial #;vanc_alluvial2
kbl(vanc_exp_t, booktabs = T) %>% kable_classic() %>% kable_styling("striped")

# NSAID
nsaid_alluvial #;vanc_alluvial2
kbl(nsaid_exp_t, booktabs = T) %>% kable_classic() %>% kable_styling("striped")

# NSAID + Ket
nsaid_ketorolac_alluvial
kbl(nsaid_ket_exp_t, booktabs = T) %>% kable_classic() %>% kable_styling("striped")
```

```{r, include=FALSE}
# # Save tables and images
# # Save the frequency-based plot
ggsave("fig1_f_plot.png",plot = sb2, width = 14, height = 6, dpi = 300)
# # Save the relative frequency plot
ggsave("fig1_rf_plot.png",plot = sb1,width = 14, height = 6, dpi = 300, units = "in")
# # Save plots 
ggsave("st_vanc_rf.png", plot = p1, width = 12, height = 6, dpi = 300)
ggsave("st_vanc_f.png", plot = p2, width = 12, height = 6, dpi = 300)
ggsave("st_calc_rf.png", plot = p3, width = 12, height = 6, dpi = 300)
ggsave("st_calc_F.png", plot = p4, width = 12, height = 6, dpi = 300)
# 
# ## Save to a CSV file
write.csv(tab3Mat_overall, file ="table3_NTMX.csv")
# ## Save to a CSV file
write.csv(tab2Mat_overall, file ="table2_NTMX.csv")
# ## Save to a CSV file
write.csv(tab2Mat_vanc, file ="table2_vanc.csv")
# ## Save to a CSV file
write.csv(tab1Mat_overall, file ="table1_overall.csv")

ggsave("alluvial_vanc.png", plot = vanc_alluvial, width = 12, height = 6, dpi = 300)
#ggsave("alluvial_vanc_stage.png", plot = vanc_alluvial2, width = 12, height = 6, dpi = 300)

ggsave("alluvial_nsaid.png", plot = nsaid_alluvial, width = 12, height = 6, dpi = 300)
ggsave("alluvial_NK.png", plot = nsaid_ketorolac_alluvial, width = 12, height = 6, dpi = 300)

```
