---
title: "ninja_dc"
author: "Casey Sakamoto"
date: "`r Sys.Date()`"
output: html_document
---

# Step 1
- run the program within the "p00005 chronology of exposure" file: "ninjapicu_data_nohdrs" -- I outputted this generated data to a file called "redcap" in the data folder
- this redcap data set will be the basis for "imported_dataset"

```{r setup, include = FALSE}
library(readr)
# import redcap data set derived in above nested program 
redcap <- read_csv("S:/Brinton/Nephrology/2024.03.06 Shih NINJA - RAI mephrotoxin exposures in ICU and clincal course retrospective cohort/data/redcap.csv")

# NUMBERS AND CORRESPONDING MEDS
# List of exposure numbers and corresponding names based on the previous function calls
exposure_list <- data.frame(
  ExposureNumber = c(48, 12, 49, 13, 50, 14, 15, 51, 44, 16, 
                     17, 18, 19, 20, 21, 22, 52, 42, 53, 23, 
                     24, 25, 26, 27, 47, 30, 28, 54, 43, 29, 
                     55, 56, 31, 57, 32, 58, 59, 60, 33, 61, 
                     62, 34, 35, 36, 63, 37, 38, 39, 40, 45, 
                     46, 64, 65, 41),
  
  ExposureName = c("Acyclovir", "Ambisome", "Amphotericin_Con", "Amikacin", "Aspirin", 
                   "Captopril", "Carboplatin", "Celecoxib", "Cisplatin", "Cefotaxime",
                   "Ceftazidime", "Cefuroxime", "Cidofovir", "Colistimethate", "Cyclosporine", 
                   "Dapsone", "Deferasirox", "Enalapril", "Enalaprilat", "Foscarnet", 
                   "Gadolineum_Derivatives", "Ganciclovir", "Gentamicin", "Ibuprofen", 
                   "Ketorolac", "Ifosfamide", "Iodinated_CA", "Indomethacin", "Lisinopril", 
                   "Lithium", "Losartan", "Mesalamine", "Methotrexate", "Mitomycin", "Nafcillin", 
                   "Naproxen", "Pamidronate", "Pentamidine_IV", "Zosyn_Piperacillin", "Polymyxin_B", 
                   "Sacubitril_Valsartan", "Sirolimus", "Sulfasalazine", "Tacrolimus", "Tenofovir", 
                   "Ticarcillin_CA", "Tobramycin", "Topiramate", "Vancomycin", "Valganciclovir", 
                   "Valacyclovir", "Valsartan", "Zoledronic_Acid", "Zonisamide")
)
```

```{r macrotofunction}
# Function to convert "checked" to 1 and "unchecked" to 0 by col prefix name
convert_checked_by_prefix <- function(df, prefix) {
  # Get the column names that start with the specified prefix
  selected_cols <- grep(paste0("^", prefix), names(df), value = TRUE)
  
  # Loop through the selected columns and convert "Checked" to 1 and "Unchecked" to 0
  df[selected_cols] <- lapply(df[selected_cols], function(x) {
    ifelse(x == "Checked", 1, ifelse(x == "Unchecked", 0, x))
  })
  
  return(df)
}

convert_to_numeric_by_prefix <- function(df, prefix) {
  # Get the column names that start with the specified prefix
  selected_cols <- grep(paste0("^", prefix), names(df), value = TRUE)
  
  # Convert the selected columns to numeric
  df[selected_cols] <- lapply(df[selected_cols], as.numeric)
  
  return(df)
}




# MACRO count_exp
# Function to calculate exposure counts
count_exp <- function(num, name, data) {
  count_col <- paste0("count_", num, "_", name)
  data[[count_col]] <- rowSums(data[, 
    c(paste0("ntmx_3_days_prior___", num), paste0("ntmx_2_days_prior___", num),
      paste0("ntmx_1_days_prior___", num), paste0("ntmx_day_of___", num),
      paste0("ntmx_day_of_1___", num), paste0("ntmx_day_of_2___", num),
      paste0("ntmx_day_of_3___", num), paste0("ntmx_day_of_4___", num),
      paste0("ntmx_day_of_5___", num), paste0("ntmx_day_of_6___", num),
      paste0("ntmx_day_of_7___", num))], na.rm = TRUE)
  return(data)
}

# MACRO day_exp
# Function to calculate day exposure
day_exp <- function(num, name, data) {
  day_col <- paste0("day_", num, "_", name)
  data[[day_col]] <- NA  # Initialize with NA
  
  # Sequentially check conditions and assign day values
  data[[day_col]] <- ifelse(data[[paste0("ntmx_3_days_prior___", num)]] == 1, -3, data[[day_col]])
  data[[day_col]] <- ifelse(is.na(data[[day_col]]) & data[[paste0("ntmx_2_days_prior___", num)]] == 1, -2, data[[day_col]])
  data[[day_col]] <- ifelse(is.na(data[[day_col]]) & data[[paste0("ntmx_1_days_prior___", num)]] == 1, -1, data[[day_col]])
  data[[day_col]] <- ifelse(is.na(data[[day_col]]) & data[[paste0("ntmx_day_of___", num)]] == 1, 0, data[[day_col]])
  data[[day_col]] <- ifelse(is.na(data[[day_col]]) & data[[paste0("ntmx_day_of_1___", num)]] == 1, 1, data[[day_col]])
  data[[day_col]] <- ifelse(is.na(data[[day_col]]) & data[[paste0("ntmx_day_of_2___", num)]] == 1, 2, data[[day_col]])
  data[[day_col]] <- ifelse(is.na(data[[day_col]]) & data[[paste0("ntmx_day_of_3___", num)]] == 1, 3, data[[day_col]])
  data[[day_col]] <- ifelse(is.na(data[[day_col]]) & data[[paste0("ntmx_day_of_4___", num)]] == 1, 4, data[[day_col]])
  data[[day_col]] <- ifelse(is.na(data[[day_col]]) & data[[paste0("ntmx_day_of_5___", num)]] == 1, 5, data[[day_col]])
  data[[day_col]] <- ifelse(is.na(data[[day_col]]) & data[[paste0("ntmx_day_of_6___", num)]] == 1, 6, data[[day_col]])
  data[[day_col]] <- ifelse(is.na(data[[day_col]]) & data[[paste0("ntmx_day_of_7___", num)]] == 1, 7, data[[day_col]])
  
  return(data)
}


```

```{r test zone, include = FALSE}
data_a_converted1 <- convert_checked_by_prefix(data_a, "ntmx")
# Apply the function to the data frame for columns with the prefix "ntmx"
data_a_converted2 <- convert_to_numeric_by_prefix(data_a_converted1, "ntmx")
# Print the converted data frame
# print(data_a_converted2)

```


```{r dc}
# Assuming the dataset is already imported and available as `redcap`
# Excluding specific record IDs
imported_dataset <- redcap[!(redcap$record_id %in% c(11, 35, 16, 17, 38, 48, 44, 58, 74, 18, 46, 70, 26)), ]

# Frequency table for the variable ntmx_exposure_type (with missing values included)
table(imported_dataset$ntmx_exposure_type, useNA = "ifany")
# ntmx_exposure_type missing for 23 instead of 28 people -- was this figured out?


# Create a new data frame, just like the 'data_a' step in SAS
data_a <- imported_dataset
# convert checked and unchecked into 1 and 0
data_a_converted1 <- convert_checked_by_prefix(data_a, "ntmx")
# Apply the function to the data frame for columns with the prefix "ntmx"
data_a_converted2 <- convert_to_numeric_by_prefix(data_a_converted1, "ntmx")


# we want to apply the exposure counts and day exposures

for (i in 1:length(exposure_list$ExposureNumber)){
    data_a_converted2 <- count_exp(exposure_list$ExposureNumber[i], exposure_list$ExposureName[i], data_a_converted2)
}



# Apply day_exp for all exposure groups
for (i in 1:length(exposure_list$ExposureNumber)){
data_a_converted2 <- day_exp(exposure_list$ExposureNumber[i], exposure_list$ExposureName[i], data_a_converted2)
}

# Create 'Day_01_aki' by calculating the difference between two date columns
# Assuming 'aki_episode_start_date' and 'start_date_for_ntmx_encoun' are in Date format
data_a_converted2$Day_01_aki <- as.numeric(difftime(data_a_converted2$aki_episode_start_date, 
                                          data_a_converted2$start_date_for_ntmx_encoun, 
                                          units = "days"))

# The dataset `data_a_converted2` now includes the new variables from the count_exp and day_exp functions,
# along with the Day_01_aki variable representing the number of days between the two dates.


### LEFT OFF AT LINE 243 PROC FREQ data=play;   table Day_01_aki; RUN; in chronology of exposure with aki program listed above


```
