---
title: "table3 derivations"
author: "Casey Sakamoto"
date: "2025-02-04"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(data.table)
# added in 2/3/2025 code NOTE THIS IS A 3Gig file, takes a minute to lood onto machine, lambda maybe needed
tab_3_flowsheets <- read_csv("S:/Sakamoto/Nephrology/Data/Table 3 Flowsheets Table.csv")
```

lets pull 
Weight on admission (kg) -- will need z scores later

Height on admission (cm) -- will need z scores later

BMI (use CDC staging for categorical, also report as continuous)

BSA (Body Surface Area)

```{r table 3 setup, include = FALSE}
#### TAB 3 FLOWSHEETS
# note this is a particularly large file; lets try and grab what we need and filter down to reduce comp times etc

# tab 3 work: 
# VALUETYPE counts
#    Custom List   Numeric Type Patient Height Patient Weight    String Type    Temperature 
#        120325       13081171        3375407        7718862         167131        9350901 

# FLOWSHEETROWNAME counts
#          Blood Flow (mL/min)                    Blood Flow Rate (mL/min)                                         BMI                                         BSA 
#                        33526                                     1758325                                     1073755                                     1904763 
#      BSA (Calculated - sq m)                             Circuit Changed                      Circuit Changed Reason CRRT Filter (Range 100 to 250) - DO NOT USE 
#                       805906                                         243                                         191                                       34936 
#                    CRRT Mode                  Cumulative 24 Hour Balance                        Delta P - DO NOT USE                           Dialysate (mL/hr) 
#                         8111                                       31401                                       33239                                       33582 
# Dialysate Solution (PrisMax)   Effluent (Range +50 to -150) - DO NOT USE                                 Filter Type                         Filtration Fraction 
#                        31748                                       33743                                       18635                                       34228 
#                     FiO2 (%)                                  Heart rate                                  Heart Rate                     Heart Rate (DO NOT USE) 
#                       287665                                         173                                       29998                                        2845 
#                       Height                                 MAP (cmH2O)                                  MAP (mmHg)                  Old Do Not Use Stool in mL 
#                      3375407                                       41871                                         179                                         537 
#           Ordered Fluid Goal                       Patient Hourly Intake                                 PRBC Volume                   PRBCs Volume (Do Not Use) 
#                        31638                                       31478                                          38                                       67103 
#                    RAI Score                      Reason circuit changed              Replacement Solution (PrisMax)                                        Resp 
#                         7455                                           8                                       31691                                     4598025 
#                  Respiration                            Respiratory Rate       Return (Range 50 to 150) - DO NOT USE                                  Stool (mL) 
#                         1725                                         419                                       34941                                       54369 
#                         Temp   TMP (Transmembrane Pressure) - DO NOT USE                Total Ca to Ionized Ca Ratio                Transmembrane Pressure (TMP) 
#                      9350901                                       33237                                        2728                                     1753076 
#                   Urine (mL)                          Urine Drain Output                                      Weight                       zz MAP Old do not use 
#                       438799                                       74790                                     7718862                                        7507 

# filter out values with "do not use" in them
tab_3_flowsheets <- tab_3_flowsheets %>% filter(!grepl("do not use", FlowSheetRowName, ignore.case = TRUE))

#   Custom List   Numeric Type Patient Height Patient Weight    String Type    Temperature 
#        120325       12968243        3375407        7718862          31971        9350901 

#            Blood Flow (mL/min)       Blood Flow Rate (mL/min)                            BMI                            BSA        BSA (Calculated - sq m)                Circuit Changed 
#                          33526                        1758325                        1073755                        1904763                         805906                            243 
#         Circuit Changed Reason                      CRRT Mode     Cumulative 24 Hour Balance              Dialysate (mL/hr)   Dialysate Solution (PrisMax)                    Filter Type 
#                            191                           8111                          31401                          33582                          31748                          18635 
#            Filtration Fraction                       FiO2 (%)                     Heart rate                     Heart Rate                         Height                    MAP (cmH2O) 
#                          34228                         287665                            173                          29998                        3375407                          41871 
#                     MAP (mmHg)             Ordered Fluid Goal          Patient Hourly Intake                    PRBC Volume                      RAI Score         Reason circuit changed 
#                            179                          31638                          31478                             38                           7455                              8 
# Replacement Solution (PrisMax)                           Resp                    Respiration               Respiratory Rate                     Stool (mL)                           Temp 
#                          31691                        4598025                           1725                            419                          54369                        9350901 
#   Total Ca to Ionized Ca Ratio   Transmembrane Pressure (TMP)                     Urine (mL)             Urine Drain Output                         Weight 
#                           2728                        1753076                         438799                          74790                        7718862 


# LETS PULL weight, height, bmi, bsa and write csv so easier to clean/work with on work laptop
# tab_3_other = tab_3_flowsheets %>% filter(!(FlowSheetRowName %in% c("BMI", "BSA","Height","Weight")))

tab_3_measurements = tab_3_flowsheets  %>% filter(FlowSheetRowName %in% c("BMI", "BSA","Height","Weight"))


# note lots of "duplicate" rows where measurements are looking to be the same, but different timevalues (ie same date same weight, two different time values)
mymean = function(x){mean(x, na.rm=T)}
tab_3_measurements_wide = tab_3_measurements %>% group_by(ArbPersonID, DaysFromDOBtoValue, FlowSheetRowName) %>% 
  summarize(Value = mean(Value, .groups = "drop"))  %>%
  pivot_wider(names_from = c("FlowSheetRowName"), values_from = "Value", values_fn = mymean)

```


```{r}
# HEIGHT WEIGHT Z SCORES -- used in tandem with some datasets derived in child_analytic_cohort
# Load dataset
AKI_COMPASS_DATA_T3 <-tab_3_flowsheets %>%
  filter(FlowSheetRowName %in% c('BSA (Calculated - sq m)', 'Current BSA', 'Dosing Weight', 'Height', 'Weight') |
         FlowSheetRowName %in% c('HEIGHT', 'R UCH IP BSA', 'R UCH IP DOSING WEIGHT', 'WEIGHT/SCALE') |
         ValueType %in% c('Patient Height', 'Patient Weight'))

# Merge datasets
LEFT1 <- merge(first_X_age, AKI_COMPASS_DATA_T3, by = "ArbPersonID", all.x = TRUE)

# Extract weight-related data
LEFT1_Weight <- LEFT1 %>%
  filter(FlowSheetRowName %in% c('Dosing Weight', 'Weight') |
         FlowSheetRowName %in% c('R UCH IP DOSING WEIGHT', 'WEIGHT/SCALE') |
         ValueType %in% c('Patient Weight')) %>%
  mutate(day = DaysFromDOBtoValue - AgeDays,
         ABS_DAY = abs(day)) %>%
  filter(abs(day) <= 365) %>%
  rename(weight_oz = Value)

# Extract height-related data
LEFT1_Height <- LEFT1 %>%
  filter(FlowSheetRowName %in% c('Height') |
         FlowSheetRowName %in% c('HEIGHT') |
         ValueType %in% c('Patient Height')) %>%
  mutate(day = DaysFromDOBtoValue - AgeDays,
         ABS_DAY = abs(day)) %>%
  filter(abs(day) <= 365) %>%
  rename(height_in = Value)

# Extract BSA-related data
LEFT1_BSA <- LEFT1 %>%
  filter(FlowSheetRowName %in% c('BSA (Calculated - sq m)', 'Current BSA') |
         FlowSheetRowName %in% c('R UCH IP BSA')) %>%
  mutate(day = DaysFromDOBtoValue - AgeDays,
         ABS_DAY = abs(day)) %>%
  filter(abs(day) <= 365) %>%
  rename(BSA_sqm = Value)

# Select closest to baseline measurement
Left1_Weight_one <- LEFT1_Weight %>%
  arrange(ArbPersonID, ABS_DAY) %>%
  group_by(ArbPersonID) %>%
  slice(1) %>%
  select(ArbPersonID, weight_oz, Unit)

Left1_Height_one <- LEFT1_Height %>%
  arrange(ArbPersonID, ABS_DAY) %>%
  group_by(ArbPersonID) %>%
  slice(1) %>%
  select(ArbPersonID, height_in, Unit)

Left1_BSA_one <- LEFT1_BSA %>%
  arrange(ArbPersonID, ABS_DAY) %>%
  group_by(ArbPersonID) %>%
  slice(1) %>%
  select(ArbPersonID, BSA_sqm, Unit)

# Frequency tables
# table(Left1_Weight_one$Unit)
# table(Left1_Height_one$Unit)
# table(Left1_BSA_one$Unit)

# Summary statistics
# summary(as.numeric(Left1_Weight_one$weight_oz))
# summary(as.numeric(Left1_Height_one$height_in))
# summary(as.numeric(Left1_BSA_one$BSA_sqm))

# Merge all datasets
HT_WT_BSA <- reduce(list(first_X_age, Left1_Weight_one, Left1_Height_one, Left1_BSA_one), 
                     function(x, y) merge(x, y, by = "ArbPersonID", all.x = TRUE)) %>%
  select(-Unit)


# ZSCORES

# Sort and get first observation by AgeAtTimeOfAdmission
T2_oneobs <- AKI_COMPASS_DATA_T2 %>%
  arrange(ArbPersonID, desc(AgeDays)) %>%
  group_by(ArbPersonID) %>%
  slice(1) %>%
  ungroup()

# Merge datasets to create FOR_Zscore
tables_to_merge <- list(AKI_COMPASS_DATA_T1 %>% mutate(BOB = TRUE), first_X_age, HT_WT_BSA, T2_oneobs)
FOR_Zscore <- Reduce(function(x, y) merge(x, y, by = "ArbPersonID", all.x = TRUE), tables_to_merge) %>%
  filter(BOB) %>%
  select(-BOB)

play <- FOR_Zscore # save progress on the play dataset
play$weight_oz = as.numeric(play$weight_oz)
play$height_in = as.numeric(play$height_in)
play$BSA_sqm = as.numeric(play$BSA_sqm)
play$Sex = ifelse(play$Sex == "Unknown", NA, play$Sex)
play$weight_kg = play$weight_oz*0.0283495
play$height_cm = ifelse(play$height_in==0,NA,round(play$height_in*2.54,1))
play = play %>% mutate(sex12 = case_when(Sex == "Male" ~ 1, Sex == "Female" ~ 2, TRUE ~ NA))

play = play %>% select(ArbPersonID:Death_YN, weight_oz:BaselineResultValue)
# Include external BMI calculation script
source("D:/Repositories/Nephrology/COMPASS/p0001_r_translate.R")

data <- data %>%
  mutate(    waz = getWGS(secondPart = age_months,sexObserved= sex, firstPart=weight_kg, index = "wfa")
  )
test = getWGS(sexObserved = data$sex, firstPart = data$weight_kg, secondPart = data$age_months, index = "wfa")

# Filter and select relevant variables
Z <- _CDCDATA %>%
  filter(age <= 18) %>%
  select(age, ArbPersonID, AgeAtTimeOfAdmission, weight_oz, height_in, bsa_sqmet,
         waz, wapct, bmi, bmiz, bmipct, haz, hapct, _Fwaz, _Fbmiz, _Fhaz)

# Summary statistics
summary(Z %>% select(age, weight_oz, height_in, bsa_sqmet, waz, wapct, bmi, bmiz, bmipct, haz, hapct, _Fwaz, _Fbmiz, _Fhaz))

# Merge play and Z
tables_to_merge_final <- list(play, Z)
aki_t123_firstobs_Z <- Reduce(function(x, y) merge(x, y, by = "ArbPersonID", all.x = TRUE), tables_to_merge_final)

# Export to CSV
write.csv(aki_t123_firstobs_Z, "H:/From CBC Individual/BrintonJ/AKI/2022.02.15 Health Data Compass Manuscript 1/data/aki_t123_firstobs.csv", row.names = FALSE)

# Save dataset
saveRDS(aki_t123_firstobs_Z, "H:/From CBC Individual/BrintonJ/AKI/2022.02.15 Health Data Compass Manuscript 1/data/wft.rds")

# # Load dataset into library
# saveRDS(aki_t123_firstobs_Z, "H:/From CBC Individual/BrintonJ/AKI/2022.02.15 Health Data Compass Manuscript 1/data/AKI_T123_firstobs_Z.rds")
# AKI_T123_firstobs_Z <- readRDS("H:/From CBC Individual/BrintonJ/AKI/2022.02.15 Health Data Compass Manuscript 1/data/AKI_T123_firstobs_Z.rds")

# Univariate analysis
# hist(AKI_T123_firstobs_Z$AgeAtTimeOfAdmission, breaks = seq(0, 85, 1), main = "Age at Time of Admission", xlab = "Age")
# hist(AKI_T123_firstobs_Z$AgeAtTimeOfAdmission[AKI_T123_firstobs_Z$AgeAtTimeOfAdmission <= 18], 
#      breaks = seq(0, 18, 1), main = "Age at Time of Admission (<=18)", xlab = "Age")


```


```{r csv write}
### DO NOT RUN UNLESS READY

# long form with bmi, ht wt, bsa
# write_csv2(tab_3_measurements, "tab_3_ht_wt_bmi_bsa.csv")

# wide form with mean taken for multiple date/times -- doesnt look like this changes any values at cursory glance of first ~ 5 values where this would occur
write_csv2(tab_3_measurements_wide, "tab_3_meas_wide.csv")
write_csv2(AKI_COMPASS_DATA_T3, "tab_3_wt_ht.csv")

# Save johns table 1 height weight bsa dataset
write.csv2(HT_WT_BSA, "HT_WT_BSA.csv")
write.csv2(play, "play.csv")


```